// IMPORTANT! This file is autogenerated by the `type-safe-next-routes`
// package. You should _not_ update these types manually...

declare module "next-type-safe-routes" {
  type Query = { [key: string]: any };
  export type TypeSafePage =
    | "/auth-showcase"
    | { route: "/auth-showcase"; query?: Query }
    | {
        route: "/build/[gameId]/deck/[deckId]/[cardId]";
        params: {
          gameId: string | number;
          deckId: string | number;
          cardId: string | number;
        };
        query?: Query;
      }
    | {
        route: "/build/[gameId]/deck/[deckId]";
        params: { gameId: string | number; deckId: string | number };
        query?: Query;
      }
    | {
        route: "/build/[gameId]/deck";
        params: { gameId: string | number };
        query?: Query;
      }
    | {
        route: "/build/[gameId]/entity/[entityId]";
        params: { gameId: string | number; entityId: string | number };
        query?: Query;
      }
    | {
        route: "/build/[gameId]/entity";
        params: { gameId: string | number };
        query?: Query;
      }
    | {
        route: "/build/[gameId]/events";
        params: { gameId: string | number };
        query?: Query;
      }
    | {
        route: "/build/[gameId]";
        params: { gameId: string | number };
        query?: Query;
      }
    | {
        route: "/build/[gameId]/reaction/[reactionId]";
        params: { gameId: string | number; reactionId: string | number };
        query?: Query;
      }
    | {
        route: "/build/[gameId]/reaction";
        params: { gameId: string | number };
        query?: Query;
      }
    | "/build"
    | { route: "/build"; query?: Query }
    | "/"
    | { route: "/"; query?: Query }
    | {
        route: "/play/[gameId]";
        params: { gameId: string | number };
        query?: Query;
      };
  export type TypeSafeApiRoute =
    | { route: "/api/auth"; path: string; query?: Query }
    | {
        route: "/api/trpc/[trpc]";
        params: { trpc: string | number };
        query?: Query;
      };
  export const getPathname: (
    typeSafeUrl: TypeSafePage | TypeSafeApiRoute
  ) => string;
  export const getRoute: (
    typeSafeUrl: TypeSafePage | TypeSafeApiRoute
  ) => string;
}
