on:
  workflow_call:
    secrets:
      CYPRESS_PROJECT_ID:
        description: "Cypress project ID"
        required: false
    inputs:
      name:
        description: "Name of test"
        required: true
        type: string
      width:
        description: "Cypress viewport width"
        required: true
        type: number
      height:
        description: "Cypress viewport height"
        required: true
        type: number
jobs:
  run:
    name: ${{ inputs.width}}x${{ inputs.height }}
    runs-on: ubuntu-latest
    container: cypress/included:10.7.0
    services:
      db:
        image: mariadb:latest
        ports: [3306]
        env:
          MYSQL_USER: deckforge
          MYSQL_PASSWORD: deckforge
          MYSQL_DATABASE: deckforge
          MYSQL_ROOT_PASSWORD: deckforge
          MYSQL_ROOT_HOST: "%"
    env:
      DATABASE_URL: "mysql://deckforge:deckforge@db:3306/deckforge"
      VITE_AUTH_IMPLEMENTATION: "fake"
      CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
      CYPRESS_BASE_URL: http://localhost:4173
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"

      - name: Install project dependencies
        run: yarn --prefer-offline

      - name: Directory access permissions
        run: |
          chmod -R a+rwX ./node_modules/.prisma
          mkdir ./node_modules/.vite && chmod -R a+rwX ./node_modules/.vite
          chmod -R a+rwX ./cypress
          chmod -R a+rwX ./prisma
      - name: Push database
        run: yarn db:push

      - name: Seed database
        run: yarn db:seed

      - name: Run e2e tests
        run: yarn test:e2e
        env:
          CYPRESS_VIEWPORT_WIDTH: ${{ inputs.width }}
          CYPRESS_VIEWPORT_HEIGHT: ${{ inputs.height }}

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots-${{ inputs.name }}
          path: cypress/screenshots

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-videos-${{ inputs.name }}
          path: cypress/videos
